trainer: latent

dataset:
  # - src: /home/jovyan/working/gemnet_oc/gemnet_oc/scratch/lmdb_example
  # - src: /home/jovyan/shared-datasets/OC20/s2ef/all/val_id
  #   normalize_labels: True
  #   target_mean: -0.7554450631141663
  #   target_std: 2.887317180633545
  #   grad_target_mean: 0.0
  #   grad_target_std: 2.887317180633545
  # - src: /home/jovyan/shared-datasets/OC20/s2ef/all/val_id
  # - src: /home/jovyan/shared-datasets/OC20/s2ef/all/val_id
  - src: /home/jovyan/shared-datasets/OC20/s2ef/2M/train
    normalize_labels: True
    target_mean: -0.7554450631141663
    target_std: 2.887317180633545
    grad_target_mean: 0.0
    grad_target_std: 2.887317180633545
  - src: /home/jovyan/shared-datasets/OC20/s2ef/2M/train
  - src: /home/jovyan/shared-datasets/OC20/s2ef/2M/train

logger: tensorboard

task:
  dataset: trajectory_lmdb
  description: "Regressing to energies and forces for DFT trajectories from OCP"
  type: regression
  metric: mae
  labels:
    - potential energy
  grad_input: atomic forces
  train_on_free_atoms: True
  eval_on_free_atoms: True