trainer: latent

dataset:
  # - src: /home/jovyan/working/gemnet_oc/gemnet_oc/scratch/lmdb_example
  # - src: /home/jovyan/shared-datasets/OC20/s2ef/all/val_id
  - src: /home/jovyan/working/gemnet_oc/gemnet_oc/scratch/lmdb_example
  - src: /home/jovyan/working/gemnet_oc/gemnet_oc/scratch/lmdb_example
  - src: /home/jovyan/working/gemnet_oc/gemnet_oc/scratch/lmdb_example

logger: tensorboard

task:
  dataset: trajectory_lmdb
  description: "Regressing to energies and forces for DFT trajectories from OCP"
  type: regression
  metric: mae
  labels:
    - potential energy
  grad_input: atomic forces
  train_on_free_atoms: True
  eval_on_free_atoms: True