trainer: forces

logger: wandb

task:
  dataset: trajectory_lmdb
  description: "Regressing to energies and forces for DFT trajectories from OCP"
  type: regression
  metric: mae
  primary_metric: forces_mae
  labels:
    - potential energy
  grad_input: atomic forces
  train_on_free_atoms: True
  eval_on_free_atoms: True
  relaxation_steps: 300
  write_pos: True
  relax_dataset:
    src: /checkpoint/electrocatalysis/relaxations/features/init_to_relaxed/test/ood_both/data.lmdb
  relax_opt:
    name: lbfgs
    maxstep: 0.04
    memory: 50
    damping: 1.0
    alpha: 70.0
    traj_dir: /checkpoint/abhshkdz/ocp_oct1_logs/relaxations/2021_10_27_gemnet_q_md_all_anuroop/test/ood_both

dataset:
  - src: /checkpoint/electrocatalysis/relaxations/features/struct_to_energy_forces/train/md38M_efall/
    normalize_labels: True
    target_mean: -0.7554450631141663
    target_std: 2.887317180633545
    grad_target_mean: 0.0
    grad_target_std: 2.887317180633545
  - src: /checkpoint/electrocatalysis/relaxations/features/struct_to_energy_forces/val/id_30k/

model:
  name: gemnet_dev
  num_spherical: 7
  num_radial: 128
  num_blocks: 6
  emb_size_atom: 256
  emb_size_edge: 1024
  emb_size_trip_in: 64
  emb_size_trip_out: 128
  emb_size_quad_in: 64
  emb_size_quad_out: 32
  emb_size_aint_in: 64
  emb_size_aint_out: 64
  emb_size_rbf: 32
  emb_size_cbf: 16
  emb_size_sbf: 64
  num_before_skip: 2
  num_after_skip: 2
  num_concat: 4
  num_atom: 3
  num_output_afteratom: 3
  cutoff: 12.0
  cutoff_qint: 12.0
  cutoff_aeaint: 12.0
  cutoff_aint: 12.0
  max_neighbors: 30
  max_neighbors_qint: 8
  max_neighbors_aeaint: 20
  max_neighbors_aint: 1000
  rbf:
    name: gaussian
  envelope:
    name: polynomial
    exponent: 5
  cbf:
    name: spherical_harmonics
  sbf:
    name: legendre_outer
  extensive: True
  output_init: HeOrthogonal
  activation: silu
  scale_file: /private/home/abhshkdz/projects/ocp-modeling-dev/experimental/abhshkdz/gemnet/gemnet_q/scaling_factors/gemnet_base_nb6_ed1024_qin64_tout128_rbf32_sbf64_ncat4.pt

  regress_forces: True
  direct_forces: True
  forces_coupled: False

  quad_interaction: True
  atom_edge_interaction: True
  edge_atom_interaction: True
  atom_interaction: True

  num_atom_emb_layers: 2
  num_global_out_layers: 2
  qint_tags: [1, 2]
  symmetric_edge_symmetrization: False

optim:
  batch_size: 4
  eval_batch_size: 4
  load_balancing: atoms
  eval_every: 5000
  num_workers: 2
  lr_initial: 2.e-4
  optimizer: AdamW
  optimizer_params: {"amsgrad": True}
  scheduler: ReduceLROnPlateau
  mode: min
  factor: 0.8
  patience: 3
  max_epochs: 80
  force_coefficient: 100
  energy_coefficient: 1
  ema_decay: 0.999
  clip_grad_norm: 10
  loss_energy: mae
  loss_force: l2mae
  weight_decay: 0  # 2e-6 (TF weight decay) / 1e-4 (lr) = 2e-2

slurm:
  constraint: "volta32gb"
